### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by mortezarajabi** [insenseanalytics/laravel-nova-permission#1]
I've installed and did all the steps. But when I access a resource, the index page stays in the loading state. When checked the network tab, in browser dev tools, I found that the request returns an Error 500. I user the spatie/laravel-permission in my project and it works well. but in Nova, it is not working. 
I had the same issue in Nova when I applied the build in Laravel policies.

**Comment by paras-malhotra** [comment]
@mortezarajabi I'm not able to replicate this issue. Can you please paste the stacktrace?

**Comment by mortezarajabi** [comment]
I checked the apache log files and due to PHP memory limit, it was not working.
