### ISSUE TITLE
Support for Laravel-Permission 3.0 & L6.0

### ISSUE THREAD

**Issue by skillcraft-io** [insenseanalytics/laravel-nova-permission#21]
The package cannot be install with Laravel 6.0 which requires Spaties Permission Pakcage to be ^3.0.

**Comment by Myhashing** [comment]
please update this package , can not install on laravel 6.+

**Comment by Athuli7** [comment]
This is an issue

**Comment by tumainimosha** [comment]
There is an open PR for this #19 . Would be great to have it merged

**Comment by zkmark** [comment]
Does this package no longer work with Laravel 6?
