### ISSUE TITLE
This packaged is outdated needs upgrade

### ISSUE THREAD

**Issue by lawrencebosumbe** [insenseanalytics/laravel-nova-permission#23]
This package is outdated. Is no longer valid for Spatie 3,3 can you update the package?
![2019-12-04](https://user-images.githubusercontent.com/11549492/70176763-b2b6d280-16e1-11ea-8841-7d58fc8dd386.png)

**Comment by lawrencebosumbe** [comment]
It's denied by Spatie 3

**Comment by zkmark** [comment]
use this https://novapackages.com/packages/vyuldashev/nova-permission
