### ISSUE TITLE
Overriding resource permissions

### ISSUE THREAD

**Issue by chbbc** [insenseanalytics/laravel-nova-permission#7]
Hi,

My issue: when a resource had some state, it can't be updated or deleted. In policies is quite easy:

````php
class QuestionPolicy
{
    use HandlesAuthorization;

    public function update(User $user, Questao $questao)
    {
        return $question->editable();
    }
     
    public function delete(User $user, Questao $questao)
    {
        return $question->editable();
    }

etc.
`````

But, with this package, I had to override the ``authorizeTo()`` and ``authorizedTo()`` methods in the resource.

````php
    public function authorizeTo(Request $request, $ability)
    {
        if (($ability == 'update' || $ability == 'delete') && static::hasPermissionsTo($request, $ability)) {
            throw_unless($this->editable(), AuthorizationException::class);
        }
        
        throw_unless($this->authorizedTo($request, $ability), AuthorizationException::class);
    }

    public function authorizedTo(Request $request, $ability)
    {
        if (($ability == 'update' || $ability == 'delete') && static::hasPermissionsTo($request, $ability) ) {

            return $this->editable();
        }

        return static::authorizable() ? static::hasPermissionsTo($request, $ability) : true;
    }
````

Is it the right approach? 

Thank you!

**Comment by paras-malhotra** [comment]
If you want to use policies, just don't pull in the `PermissionsBasedAuthTrait` trait. You can't have both permissions based authorization and policies. You must choose one method.

**Comment by chbbc** [comment]
> If you want to use policies, just don't pull in the `PermissionsBasedAuthTrait` trait. You can't have both permissions based authorization and policies. You must choose one method.

I know that, I put the police as an example only.

My question is if there's another way to do that or is it the right approach override the ``authorizeTo()`` and ``authorizedTo()`` methods.

**Comment by paras-malhotra** [comment]
@chbbc you would not need to override those methods if you don't pull in the trait. Make sure that the trait isn't pulled in the base Resource class.
